# Generated by Django 5.0.1 on 2024-04-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
