# Generated by Django 5.0.1 on 2024-04-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_details',
            name='poster',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
